version: '3.7'
services:
  db:
    container_name: db
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_app
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
  app:
    container_name: app
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: todo_app